name: dayton_human_relations_council
description: A new Flutter project.

version: 1.0.8+8

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.0.0
  cupertino_icons: ^1.0.3
  equatable: ^2.0.3
  expandable: ^5.0.1
  flutter_bloc: ^7.0.1
  flutter_form_builder: ^6.0.1
  get_it:
  http: ^0.13.3
  intl: ^0.17.0
  package_info: ^2.0.2
  rxdart: ^0.27.1
  shared_preferences: ^2.0.6
  url_launcher: ^6.0.8
  uuid: ^3.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf
          style: italic
