name: dayton_human_relations_council
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^2.5.0
  cupertino_icons: ^1.0.0
  equatable: ^1.2.5
  flutter_bloc: ^6.1.1
  flutter_form_builder: ^4.2.0
  get_it: ^5.0.3
  http: ^0.12.2
  package_info: ^0.4.3+2
  rxdart: ^0.25.0
  shared_preferences: ^0.5.12+4
  url_launcher: ^5.7.10
  uuid: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf
          style: italic
